#!/bin/bash
VER=0.0.1
echo making pbc_bce-$VER
GREPVER=${VER//\./\\.}
git log > ChangeLog
cat ChangeLog | head -20 | grep pbc_bce-$GREPVER > /dev/null || {
    echo git log does not mention release 
    exit 1
}
TMPDIR=`mktemp -d` || {
    echo Error creating temp directory
    exit 1
}
echo git diff: ideally should do nothing...
git diff
WORKDIR=$TMPDIR/pbc_bce-$VER
git archive --format=tar --prefix=pbc_bce-$VER HEAD | tar xvC $TMPDIR
HERE=`pwd`
cp ChangeLog $WORKDIR
cd $WORKDIR
grep $GREPVER NEWS > /dev/null || {
    echo NEWS does not mention release 
    cd $HERE
    rm -rf $TMPDIR
    exit 1
}
cd $TMPDIR
echo Creating tarball...
tar cvfz $HERE/pbc_bce-$VER.tar.gz pbc_bce-$VER
